### ISSUE TITLE
Hi, might be a stupid question

### ISSUE THREAD

**Issue by Hyle33ies** [iShohei220/adopt#1]
Nice work. Just have one dumb question: how to install the optimizer? I have PyTorch>=2.4.0 and update my pip, but cannot find a package called adopt.

**Comment by iShohei220** [comment]
Thank you for being interested in our work.

To use ADOPT, you should copy [`adopt.py`](https://github.com/iShohei220/adopt/blob/main/adopt.py) into your code and import it.

We are planning to make it available as a `pip` package, but it is not currently supported, so you need to manually import it at the moment.

Thanks.

**Comment by Hyle33ies** [comment]
Got it! Thanks for the reply.
