### ISSUE TITLE
All loses in first epoch give Nan errors

### ISSUE THREAD

**Issue by adeerkhan** [iShohei220/adopt#10]
All loses in first epoch give Nan error. I've been training an auto-encoder for a GPT model. 
It goes from Epoch 0 to 1 to 2, and there is no exception or error throw-up, but the losses are in NAN.
Anyone knows the error or have they tested on transformer or GPTs?

**Comment by iShohei220** [comment]
Thank you for your report.

We fixed the instability of the original implementation in the commit on Nov 22, so please try the updated version.
If it is still unstable, please report it again.

Thanks!
