### ISSUE TITLE
Actually requires torch 2.5+?

### ISSUE THREAD

**Issue by dx2-66** [iShohei220/adopt#4]
The code in the repository seems to require a newer torch version than stated. At least it fails with 2.4.0 for me:

`ImportError: cannot import name '_device_dtype_check_for_fused' from 'torch.optim.optimizer'`

Backtracking the torch commit that causes this shows that the changes are trivial, but should probably require different branches for different torch versions compatibility.

In case anyone encountered the same problem, here's a fork with my solution: https://github.com/dx2-66/adopt/tree/actual-torch-2.4 (a pull request into main would likely be excessive).

**Comment by iShohei220** [comment]
Thank you for pointing it out.
It seems true that the current implementation is not compatible with PyTorch 2.4.x, so we've modified README.
