### ISSUE TITLE
missing _fused_adopt

### ISSUE THREAD

**Issue by winglian** [iShohei220/adopt#7]
in this line https://github.com/iShohei220/adopt/blob/main/adopt.py#L486
there seems to be an undefined variable `_fused_adopt` that doesn't exist anywhere

**Comment by iShohei220** [comment]
Thank you for pointing it out.
We've fixed it in the latest commit.

Note that we are not currently supporting the fused implementation, so setting `fused=True` leads to [RuntimeError](https://github.com/iShohei220/adopt/blob/main/adopt.py#L83-L85).
