### ISSUE TITLE
Lower perfoemance

### ISSUE THREAD

**Issue by bolbolamir** [iShohei220/adopt#8]
Hello, hope you are doing great!
This is not an issue in its traditional terms, sorry about that.
I experimented with your implementation on cifar10 using resnet18 from torchvision and the performance was much worse compared to the Adam, I even used three different LRs and the results weren't even comparable to Adam. 
I wanted to know the reason, given that my code is not buggy.

**Comment by Tony-Y** [comment]
I experienced a worse performance of ResNet20 on CIFAR10, but I got a comparable performance when using a linear warmup.

No Warmup:
![__results___8_0](https://github.com/user-attachments/assets/a0a179ad-b235-4017-9c86-6fe2069873e8)


Linear Warmup:
![__results___8_0-2](https://github.com/user-attachments/assets/bde58cf0-7923-45e5-b7d8-f3d404a7278b)

**Comment by iShohei220** [comment]
Thank you for your report.

As you mentioned, the original implementation of ADOPT seemed to get unstable sometimes, so we have slightly modified it to improve the stability in the commit on Nov 22 (see README for more details).
Please try the updated version by using the latest main branch, and if it is still unstable, please report it again.

Thanks!
